#!/usr/bin/python

import re
import subprocess
import sys

description = subprocess.check_output(["git", "describe"]).strip()
match = re.match(r"v([\d\.]+)", description)
if match:
    version = match.groups()[0]

    if version != description[1:]:
        version = version + "git"

    sys.stdout.write(version)
else:
    raise Exception("Unknown version. Please create an annotated tag.")
