#!/usr/bin/python

import re
import subprocess
import sys

description = subprocess.check_output(["git", "describe"])
match = re.match(r"v([\d\.]+)", description)
if match:
    version = match.groups()[0]

    if version != description:
        commit_id = subprocess.check_output(["git", "rev-parse", "--short",
                                             "HEAD"])
        version = "%sgit%s" % (version, commit_id)

    sys.stdout.write(version)
else:
    raise Exception("Unknown version. Please create an annotated tag.")
