#!/usr/bin/python -u

# Copyright (C) 2013, Daniel Narvaez
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

config_path = "/etc/X11/Xwrapper.config"

with open(config_path) as f:
    new_config = [line for line in f.readlines()
                  if "allowed_users" not in line]

new_config.append("allowed_users=anybody\n")

with open(config_path, "w") as f:
    f.write("".join(new_config))
